### Session04 (Loop)

In [6]:
for i in range(2):
  print("python")
print("out of loop")

python
python
out of loop


In [10]:
for num in range(4):
  print(num)

0
1
2
3


In [ ]:
# range(start, stop, step)
# start ====> default : 0
# step ====> default: 1
# stop =====> xxxxxxxxx

In [14]:
for num in range(2, 7, 2): # num = 2, num = 4, num = 6
  print(num)
print("out of loop: ",num)

2
4
6
out of loop:  6


In [22]:
number = int(input("number of student: "))
for i in range(number):  # i = 0, i = 1, i = 2
  score = float(input(f"score of student_{i+1}: "))
  if score >= 10:
    print("you passed")
  else:
    print("you didn't pass")
    

you passed
you passed


In [24]:
num = int(input("number: "))
for i in range(num): # i = 0 .... i = 5
  if i % 3 == 0:
    print(i)

0
3


In [25]:
num = int(input("number: "))
for i in range(0, num, 3): # i = 0 .... i = 5
  print(i)

0
3


In [28]:
name = "python" # 0 ... 5
for i in range(6):
  print(name[i])


p
y
t
h
o
n


In [29]:
name = "python"
#        c
for c in name:
  print(c)

p
y
t
h
o
n


In [32]:
name = "aaabbb"
#         3
count_a = 0
for c in name:
  if c == "a":
    count_a += 1
print(count_a)

3


In [35]:
x = 10
print(x)
x += 5  # x = x + 5
print(x)

10
15


### break, continue

In [39]:
for i in range(6):
  score = input(f"score_{i+1}: ")
  if score == "exit":
    break
  print(float(score))

12.0


In [43]:
for number in range(7,10):
  print("number: ", number)

for number in range(11,14):
  print("number: ", number)

number:  7
number:  8
number:  9
number:  11
number:  12
number:  13


In [54]:
for number in range(7,14):
  print(number, end=",")
  print("python", end=",")
  if number == 8:
    continue
  print("java", end=",")
  print("c++", end=",")

7,python,java,c++,8,python,9,python,java,c++,10,python,java,c++,11,python,java,c++,12,python,java,c++,13,python,java,c++,

### Example

python
ython,
thon, 
hon, p
on, py
n, pyt
, pyth
 pytho
python
ython,
thon, 
hon, j
on, ja
n, jav
, java
 java,
java, 
ava, c
va, c,
a, c, 
, c, p
 c, py
c, pyt
, pyth
 pytho
python
ython
thon
hon
on
n


In [58]:
name = "python, python, java, c, python"
#       i=0
# substr = "python" ===> l1 = 6
# i = 0 + 6 . name [0:i]
substr = "python"
l1 = len(name)
for i in range(l1):
  if name[i:i+len(substr)] == substr:
    print(i)
  


0
8
25


In [ ]:
num1 = 12
max_num = num1
num2 = 13
if num2 > max_num:
  max_num = num2
num3 = 27
if num3 > max_num:
  max_num = num3
num4 = 16
if num4 > max_num:
  max_num = num4

In [63]:
score1 = float(input("your score: "))
max_score = score1
sum_score = score1
for i in range(3):
  score = float(input("score: "))
  sum_score += score
  if score > max_score:
    max_score = score
print(f"max scores: {max_score}")
avg = sum_score / 4
print(f"avg: {avg}")

max scores: 6.0
avg: 4.5


In [66]:
x = 10
print(f"result: {x}")

result: 10


In [13]:
import numpy as np
example = np.ones((6, 6, 6))
print("array:")
print(example)
example[:,:,2] = 2
print("Modified array:")
print(example)

array:
[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]]
Modified array:
[[[1. 1. 2. 1. 1. 1.]
  [1. 1. 2. 1. 1. 1.]
  [1. 1. 2. 1. 1. 1.]
  [1. 1. 2. 1. 1. 1.]
  [1. 1. 2. 1. 1. 1.]
  [1. 1. 2. 1. 1. 1.]]

 [[1. 1. 2. 1. 1. 1.]
  [1. 1. 2. 1. 1.

In [14]:
x_num = 400
y_num = 150
tau = 0.54
t_number = 2500
lattice_num = 9
import numpy as np
speed_of_all_in_x_dir = np.array([0,0,1,1,1,0,-1,-1,-1])
weights = np.array([4/9,1/9,1/36,1/9,1/36,1/9,1/36])
F = np.ones((y_num, x_num, lattice_num)) + 0.001 * np.random.rand(y_num,x_num,lattice_num)
F


array([[[1.00002318, 1.00017036, 1.00072952, ..., 1.0000498 ,
         1.00008702, 1.00078688],
        [1.00074806, 1.00084694, 1.00087022, ..., 1.00027504,
         1.00080188, 1.00096936],
        [1.00020423, 1.00065003, 1.00028922, ..., 1.00021712,
         1.00039684, 1.00001126],
        ...,
        [1.00054378, 1.00003948, 1.00097402, ..., 1.0005189 ,
         1.00049758, 1.0006089 ],
        [1.00089676, 1.00001772, 1.00030628, ..., 1.00056791,
         1.00010135, 1.00033555],
        [1.00073985, 1.00034669, 1.00084594, ..., 1.00045077,
         1.00043407, 1.00057007]],

       [[1.00013101, 1.00092591, 1.00029289, ..., 1.00076699,
         1.0006904 , 1.00013047],
        [1.00002052, 1.00085082, 1.00007817, ..., 1.0004414 ,
         1.00022399, 1.00074153],
        [1.00091315, 1.00034581, 1.00075746, ..., 1.00013177,
         1.00025291, 1.00012531],
        ...,
        [1.00090386, 1.00044396, 1.00015426, ..., 1.00093854,
         1.00030006, 1.00079097],
        [1.0

In [15]:
F.shape

(150, 400, 9)

In [26]:
F[:,:,3] = 2

In [30]:
F[0][0].shape

(9,)

In [21]:
F[0,:,3]

array([1.00068543, 1.00041296, 1.00076767, 1.00071102, 1.00045961,
       1.000461  , 1.00050312, 1.0002757 , 1.00057294, 1.00063544,
       1.00034882, 1.00098969, 1.00075311, 1.00066124, 1.00009559,
       1.00000179, 1.00026625, 1.00023781, 1.00026213, 1.00002824,
       1.00049364, 1.00047865, 1.00062179, 1.00092535, 1.0008419 ,
       1.00010521, 1.0004055 , 1.00054586, 1.00019381, 1.00012226,
       1.00068372, 1.0003834 , 1.00085818, 1.00022935, 1.00058386,
       1.00096972, 1.00051262, 1.00003933, 1.00070253, 1.00048455,
       1.00073179, 1.00096562, 1.00000248, 1.00077483, 1.00047741,
       1.00081928, 1.00061103, 1.00060558, 1.00009394, 1.00018224,
       1.00088779, 1.00088933, 1.00046597, 1.00054989, 1.000734  ,
       1.00007389, 1.00035961, 1.00060784, 1.0004698 , 1.00094615,
       1.00064384, 1.00067654, 1.00004938, 1.00030471, 1.00063888,
       1.0003499 , 1.00099235, 1.00060864, 1.00054455, 1.00069251,
       1.0009476 , 1.00024241, 1.00092684, 1.00058734, 1.00024